spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb://localhost:27017
      # noinspection SpellCheckingInspection
      database: agileinsight
      auto-index-creation: true